//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.ArticuloPrecioVentas = new HashSet<ArticuloPrecioVenta>();
            this.Componentes = new HashSet<Componente>();
            this.DetalleEntregaPlantas = new HashSet<DetalleEntregaPlanta>();
            this.DetalleFacturaCompras = new HashSet<DetalleFacturaCompra>();
            this.DetalleFacturaVentas = new HashSet<DetalleFacturaVenta>();
            this.DetalleNotaDebitoes = new HashSet<DetalleNotaDebito>();
            this.DetalleRemitoes = new HashSet<DetalleRemito>();
            this.DetalleRetiroPlantas = new HashSet<DetalleRetiroPlanta>();
            this.ListaProveedors = new HashSet<ListaProveedor>();
        }
    
        public int IDARTICULO { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> IDFAMILIA { get; set; }
        public Nullable<int> IDRUBRO { get; set; }
        public Nullable<int> IDMARCA { get; set; }
        public Nullable<int> IDTIPOARTICULO { get; set; }
        public string CODIGOFABRICA { get; set; }
        public Nullable<int> IDTIPOPRODUCTO { get; set; }
        public string IDFABRICA { get; set; }
        public string SITUACION { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public string PROCCOSTOENLISTA { get; set; }
        public Nullable<decimal> COSTOENLISTA { get; set; }
        public Nullable<int> IDPROVEEDOR { get; set; }
        public Nullable<double> UNIDADDEVENTA { get; set; }
        public string UNIDADDEMEDIDA { get; set; }
        public Nullable<double> CANT_ACTUAL { get; set; }
        public Nullable<double> CANT_DE_PUNTO_DE_PEDIDO { get; set; }
        public Nullable<double> CANTENCADAREPOSICION { get; set; }
        public Nullable<int> IDIMPUESTO { get; set; }
        public Nullable<int> IDESTADO { get; set; }
        public Nullable<double> CANTIDADOBTENIDA { get; set; }
        public byte[] IMAGEN { get; set; }
        public Nullable<int> TIPOCODIGO { get; set; }
    
        public virtual EstadoSistema EstadoSistema { get; set; }
        public virtual Familia Familia { get; set; }
        public virtual Impuesto Impuesto { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual TipoArticulo TipoArticulo { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticuloPrecioVenta> ArticuloPrecioVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Componente> Componentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEntregaPlanta> DetalleEntregaPlantas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaCompra> DetalleFacturaCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaVenta> DetalleFacturaVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNotaDebito> DetalleNotaDebitoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRemito> DetalleRemitoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRetiroPlanta> DetalleRetiroPlantas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaProveedor> ListaProveedors { get; set; }
    }
}
