//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.NotaCreditoes = new HashSet<NotaCredito>();
            this.NotaDebitoes = new HashSet<NotaDebito>();
            this.NotaPedidoes = new HashSet<NotaPedido>();
            this.Recibos = new HashSet<Recibo>();
            this.Remitoes = new HashSet<Remito>();
        }
    
        public int IDCLIENTE { get; set; }
        public string RAZONSOCIAL { get; set; }
        public Nullable<decimal> NUMDECUIT { get; set; }
        public string DOMICILIOCOMERCIAL { get; set; }
        public string LOCALIDAD { get; set; }
        public string TELEFONOSCOMERCIALES { get; set; }
        public string DOMICILIOPARTICULAR { get; set; }
        public string CONTACTO { get; set; }
        public Nullable<int> IDTIPOIVA { get; set; }
        public Nullable<int> IDESPECIALIDAD { get; set; }
        public Nullable<int> IDPERSONAL { get; set; }
        public Nullable<int> IDFORMADEPAGO { get; set; }
        public Nullable<int> IDLISTAPRECIO { get; set; }
        public Nullable<double> DIASENTREFACTURACION { get; set; }
        public Nullable<System.DateTime> ULTIMAFACTURACION { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public string NROCENTRO { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual ListaPrecio ListaPrecio { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual TipoIva TipoIva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaCredito> NotaCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaDebito> NotaDebitoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaPedido> NotaPedidoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recibo> Recibos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remito> Remitoes { get; set; }
    }
}
