//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtaCteCliente
    {
        public long IDITEM { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string NROCOMPROBANTE { get; set; }
        public string TIPOCOMPROBANTE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> DEBE { get; set; }
        public Nullable<decimal> HABER { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<decimal> MONTOPENDIENTE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PAGADO { get; set; }
        public Nullable<decimal> PENDIENTE { get; set; }
        public Nullable<decimal> IMPORTERESTANTE { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public Nullable<int> NRONOTACREDITO { get; set; }
    }
}
