//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleNotaDebito
    {
        public int IDDETALLENOTADEBITO { get; set; }
        public Nullable<int> IDARTICULO { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<double> PENDIENTE { get; set; }
        public Nullable<decimal> PRECUNITARIO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<double> PORCDESC { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> IMPUESTO1 { get; set; }
        public Nullable<decimal> IMPUESTO2 { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> NRONOTAINTERNO { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
