//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleNotaPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleNotaPedido()
        {
            this.DetalleRemitoes = new HashSet<DetalleRemito>();
        }
    
        public int IDDETALLENOTAPEDIDO { get; set; }
        public Nullable<int> IDARTICULO { get; set; }
        public int CANTIDADPEDIDA { get; set; }
        public Nullable<int> REASIGNADO { get; set; }
        public int CANTIDADRESTANTE { get; set; }
        public Nullable<int> CANTIDADAENTREGA { get; set; }
        public Nullable<decimal> PRECUNITARIO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<double> PORCDESC { get; set; }
        public Nullable<decimal> IMPUESTO1 { get; set; }
        public Nullable<decimal> IMPUESTO2 { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> IDNOTAPEDIDO { get; set; }
        public string REMITIDO { get; set; }
    
        public virtual NotaPedido NotaPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRemito> DetalleRemitoes { get; set; }
    }
}
