//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEntregaPlanta
    {
        public double ENTREGAAPLANTA { get; set; }
        public int CODIGO { get; set; }
        public Nullable<int> IDARTICULO { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<double> PENDIENTE { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<double> DETALLERETIRODEPLANTA { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
