//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRemito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleRemito()
        {
            this.DetalleFacturaVentas = new HashSet<DetalleFacturaVenta>();
        }
    
        public int IDDETALLEREMITO { get; set; }
        public Nullable<int> IDARTICULO { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public Nullable<decimal> PRECUNITARIO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<double> PORCDESC { get; set; }
        public Nullable<decimal> IMPUESTO1 { get; set; }
        public Nullable<decimal> IMPUESTO2 { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string FACTURABLE { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<double> CANTPENDIENTE { get; set; }
        public Nullable<double> DETALLEFACTURA { get; set; }
        public Nullable<int> NROREMITOINTERNO { get; set; }
        public Nullable<int> IDDETALLENOTAPEDIDO { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaVenta> DetalleFacturaVentas { get; set; }
        public virtual DetalleNotaPedido DetalleNotaPedido { get; set; }
        public virtual Remito Remito { get; set; }
    }
}
