//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRetiroPlanta
    {
        public double RETIRODEPLANTA { get; set; }
        public int IDDETALLERETIROPLANTA { get; set; }
        public Nullable<int> IDARTICULO { get; set; }
        public Nullable<double> CANTIDAD { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<double> CANTPENDIENTE { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
