//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRecibo
    {
        public int IDDETALLERECIBO { get; set; }
        public Nullable<int> IDTIPOPAGO { get; set; }
        public Nullable<int> IDSUBTIPODEPAGO { get; set; }
        public Nullable<long> NUMERO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public int NRORECIBOINTERNO { get; set; }
    
        public virtual SubtipoPago SubtipoPago { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
