//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.EmpresaCentroes = new HashSet<EmpresaCentro>();
        }
    
        public int IDEMPRESA { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string CUIT { get; set; }
        public string INGRESOBRUTO { get; set; }
        public Nullable<System.DateTime> FECHAINICIOACTIV { get; set; }
        public string DOMICILIOFISCAL { get; set; }
        public string TELEFONOCOMERCIAL { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaCentro> EmpresaCentroes { get; set; }
    }
}
