//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturasVenta()
        {
            this.DetalleFacturaVentas = new HashSet<DetalleFacturaVenta>();
        }
    
        public int NROFACTURAINTERNO { get; set; }
        public Nullable<int> NROFACTURA { get; set; }
        public string SUCURSAL { get; set; }
        public Nullable<int> IDTIPOFACTURA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDVENDEDOR { get; set; }
        public Nullable<int> IDPERSONAL { get; set; }
        public Nullable<int> IDFORMAPAGO { get; set; }
        public Nullable<decimal> BASICO { get; set; }
        public Nullable<int> PORCDESC { get; set; }
        public string DESCUENTOS { get; set; }
        public Nullable<decimal> IMPUESTO1 { get; set; }
        public Nullable<decimal> IMPUESTO2 { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<int> IDDETALLE { get; set; }
        public Nullable<bool> IMPRESA { get; set; }
        public Nullable<decimal> PAGADO { get; set; }
        public Nullable<decimal> PENDIENTE { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public string OBSERVACIONES { get; set; }
        public int NRORECIBOINTERNO { get; set; }
        public Nullable<int> IDIDENTIFICADOR { get; set; }
        public Nullable<int> IDESTADO { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
        public Nullable<int> NRONCINTERNO { get; set; }
        public Nullable<int> NRONC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaVenta> DetalleFacturaVentas { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual NotaCredito NotaCredito { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual TipoFactura TipoFactura { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
