//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturasCompra()
        {
            this.DetalleFacturaCompras = new HashSet<DetalleFacturaCompra>();
        }
    
        public int NROFACTURAINTERNO { get; set; }
        public string NROFACTURA { get; set; }
        public string SUCURSAL { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> IDTIPOFACTURA { get; set; }
        public Nullable<int> IDPROVEEDOR { get; set; }
        public Nullable<int> IDPERSONAL { get; set; }
        public Nullable<decimal> BASICO { get; set; }
        public Nullable<double> DESCUENTOS { get; set; }
        public Nullable<decimal> IMPUESTOS1 { get; set; }
        public Nullable<decimal> IMPUESTOS2 { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaCompra> DetalleFacturaCompras { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual TipoFactura TipoFactura { get; set; }
    }
}
