//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        public double NROLIQUIDACION { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> IDPERSONAL { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<int> PAGADO { get; set; }
        public string OBSERVACIONES { get; set; }
    }
}
