//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaProveedor
    {
        public int IDITEMLISTA { get; set; }
        public Nullable<int> IDPROVEEDOR { get; set; }
        public Nullable<int> IDARTICULO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<System.DateTime> FECHACOMPRA { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
