//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class connStringDB : DbContext
    {

        public connStringDB(string conectionString)
               : base("name="+conectionString)
        {
        }

        public connStringDB()
            : base("name=connStringDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulo> Articuloes { get; set; }
        public virtual DbSet<ArticuloPrecioVenta> ArticuloPrecioVentas { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Componente> Componentes { get; set; }
        public virtual DbSet<CtaCteCliente> CtaCteClientes { get; set; }
        public virtual DbSet<Detalle> Detalles { get; set; }
        public virtual DbSet<DetalleEntregaPlanta> DetalleEntregaPlantas { get; set; }
        public virtual DbSet<DetalleFacturaCompra> DetalleFacturaCompras { get; set; }
        public virtual DbSet<DetalleFacturaVenta> DetalleFacturaVentas { get; set; }
        public virtual DbSet<DetalleNotaCredito> DetalleNotaCreditoes { get; set; }
        public virtual DbSet<DetalleNotaDebito> DetalleNotaDebitoes { get; set; }
        public virtual DbSet<DetalleNotaPedido> DetalleNotaPedidoes { get; set; }
        public virtual DbSet<DetalleRecibo> DetalleRecibos { get; set; }
        public virtual DbSet<DetalleRemito> DetalleRemitoes { get; set; }
        public virtual DbSet<DetalleRetiroPlanta> DetalleRetiroPlantas { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<EmpresaCentro> EmpresaCentroes { get; set; }
        public virtual DbSet<EntregaAPlanta> EntregaAPlantas { get; set; }
        public virtual DbSet<Especialidad> Especialidads { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivils { get; set; }
        public virtual DbSet<EstadoSistema> EstadoSistemas { get; set; }
        public virtual DbSet<FacturasCompra> FacturasCompras { get; set; }
        public virtual DbSet<FacturasVenta> FacturasVentas { get; set; }
        public virtual DbSet<Familia> Familias { get; set; }
        public virtual DbSet<FormaPago> FormaPagoes { get; set; }
        public virtual DbSet<IdentificaComprob> IdentificaComprobs { get; set; }
        public virtual DbSet<Impuesto> Impuestoes { get; set; }
        public virtual DbSet<Liquidacion> Liquidacions { get; set; }
        public virtual DbSet<ListaPrecio> ListaPrecios { get; set; }
        public virtual DbSet<ListaProveedor> ListaProveedors { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<NotaCredito> NotaCreditoes { get; set; }
        public virtual DbSet<NotaDebito> NotaDebitoes { get; set; }
        public virtual DbSet<NotaPedido> NotaPedidoes { get; set; }
        public virtual DbSet<NumeradoresTabla> NumeradoresTablas { get; set; }
        public virtual DbSet<Parametro> Parametros { get; set; }
        public virtual DbSet<ParametrosReporte> ParametrosReportes { get; set; }
        public virtual DbSet<PermisoControl> PermisoControls { get; set; }
        public virtual DbSet<PermisoModulo> PermisoModuloes { get; set; }
        public virtual DbSet<PermisoUsuario> PermisoUsuarios { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Recibo> Recibos { get; set; }
        public virtual DbSet<Remito> Remitoes { get; set; }
        public virtual DbSet<RetiroPlanta> RetiroPlantas { get; set; }
        public virtual DbSet<Rubro> Rubroes { get; set; }
        public virtual DbSet<SoporteTecnico> SoporteTecnicoes { get; set; }
        public virtual DbSet<SubtipoPago> SubtipoPagoes { get; set; }
        public virtual DbSet<Suceso> Sucesoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TesoreriaCaja> TesoreriaCajas { get; set; }
        public virtual DbSet<TesoreriaMovimiento> TesoreriaMovimientoes { get; set; }
        public virtual DbSet<TesoreriaTipoMovimiento> TesoreriaTipoMovimientoes { get; set; }
        public virtual DbSet<TipoArticulo> TipoArticuloes { get; set; }
        public virtual DbSet<TipoFactura> TipoFacturas { get; set; }
        public virtual DbSet<TipoIva> TipoIvas { get; set; }
        public virtual DbSet<TipoNota> TipoNotas { get; set; }
        public virtual DbSet<TipoPago> TipoPagoes { get; set; }
        public virtual DbSet<TipoPersonal> TipoPersonals { get; set; }
        public virtual DbSet<TipoProducto> TipoProductoes { get; set; }
        public virtual DbSet<TipoRemito> TipoRemitoes { get; set; }
        public virtual DbSet<Vendedor> Vendedors { get; set; }
    }
}
