//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaCredito()
        {
            this.DetalleNotaCreditoes = new HashSet<DetalleNotaCredito>();
            this.FacturasVentas = new HashSet<FacturasVenta>();
        }
    
        public int NRONOTAINTERNO { get; set; }
        public Nullable<int> NRONOTACRED { get; set; }
        public Nullable<int> IDTIPONOTA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string SUCURSAL { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDVENDEDOR { get; set; }
        public Nullable<int> IDPERSONAL { get; set; }
        public Nullable<int> IDFORMADEPAGO { get; set; }
        public Nullable<decimal> BASICO { get; set; }
        public Nullable<double> PORCDESC { get; set; }
        public Nullable<double> DESCUENTOS { get; set; }
        public Nullable<decimal> IMPUESTO1 { get; set; }
        public Nullable<decimal> IMPUESTO2 { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<int> IDDETALLE { get; set; }
        public Nullable<int> IMPRESA { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> IDIDENTIFICADOR { get; set; }
        public Nullable<int> NRORECIBOINTERNO { get; set; }
        public Nullable<int> IDESTADO { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Detalle Detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNotaCredito> DetalleNotaCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasVenta> FacturasVentas { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual TipoNota TipoNota { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
