//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaPedido()
        {
            this.DetalleNotaPedidoes = new HashSet<DetalleNotaPedido>();
            this.Remitoes = new HashSet<Remito>();
        }
    
        public int IDNOTAPEDIDO { get; set; }
        public Nullable<int> NRONOTAPEDIDO { get; set; }
        public Nullable<System.DateTime> FECHANOTA { get; set; }
        public string SUCURSAL { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDVENDEDOR { get; set; }
        public Nullable<decimal> BASICO { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> IMPUESTO1 { get; set; }
        public Nullable<decimal> IMPUESTO2 { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public string SITUACION { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNotaPedido> DetalleNotaPedidoes { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remito> Remitoes { get; set; }
    }
}
