//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametrosReporte
    {
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<double> VALORNUMERICO { get; set; }
        public string VALORALFANUMERICO { get; set; }
    }
}
