//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int IDPARAMETROS { get; set; }
        public string VERSIONSISTEMA { get; set; }
        public string CONEXION_STRING { get; set; }
        public string DIRECCION { get; set; }
        public string NOMBREBD { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
    }
}
