//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisoUsuario
    {
        public int IdPermisoUsuario { get; set; }
        public Nullable<int> IdPersonal { get; set; }
        public Nullable<int> IdModulo { get; set; }
        public Nullable<int> IdControl { get; set; }
        public Nullable<int> IdEstadoSistema { get; set; }
    
        public virtual EstadoSistema EstadoSistema { get; set; }
        public virtual PermisoControl PermisoControl { get; set; }
        public virtual PermisoModulo PermisoModulo { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
