//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Clientes = new HashSet<Cliente>();
            this.FacturasCompras = new HashSet<FacturasCompra>();
            this.FacturasVentas = new HashSet<FacturasVenta>();
            this.NotaCreditoes = new HashSet<NotaCredito>();
            this.NotaDebitoes = new HashSet<NotaDebito>();
            this.PermisoUsuarios = new HashSet<PermisoUsuario>();
            this.Recibos = new HashSet<Recibo>();
            this.Remitoes = new HashSet<Remito>();
            this.RetiroPlantas = new HashSet<RetiroPlanta>();
        }
    
        public int IDPERSONAL { get; set; }
        public string DNI { get; set; }
        public string LEGAJO { get; set; }
        public string NOMBREYAPELLIDO { get; set; }
        public string DOMICILIO { get; set; }
        public string TELFIJO { get; set; }
        public string TELCELULAR { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public Nullable<int> IDESTADOCIVIL { get; set; }
        public Nullable<int> NRODECARTILLASANITARIA { get; set; }
        public Nullable<System.DateTime> VENCIMIENTO { get; set; }
        public string NOMBRECONYUGE { get; set; }
        public Nullable<System.DateTime> FECHANACCONYUGE { get; set; }
        public Nullable<int> IDTIPOPERSONAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public string USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public bool ISLOGIN { get; set; }
        public Nullable<int> IDESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasCompra> FacturasCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasVenta> FacturasVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaCredito> NotaCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaDebito> NotaDebitoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermisoUsuario> PermisoUsuarios { get; set; }
        public virtual TipoPersonal TipoPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recibo> Recibos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remito> Remitoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetiroPlanta> RetiroPlantas { get; set; }
    }
}
