//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Articuloes = new HashSet<Articulo>();
            this.FacturasCompras = new HashSet<FacturasCompra>();
            this.ListaProveedors = new HashSet<ListaProveedor>();
        }
    
        public int IDPROVEEDOR { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string DOMICILIO { get; set; }
        public string TELEFONOS { get; set; }
        public string CONTACTO { get; set; }
        public Nullable<int> IDRUBRO { get; set; }
        public Nullable<int> IDTIPOIVA { get; set; }
        public string NRODECUIT { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo> Articuloes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasCompra> FacturasCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaProveedor> ListaProveedors { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual TipoIva TipoIva { get; set; }
    }
}
