//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public int NRORECIBOINTERNO { get; set; }
        public Nullable<int> NRORECIBO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string SUCURSAL { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDPERSONAL { get; set; }
        public Nullable<int> IDVENDEDOR { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> IDIDENTIFICADOR { get; set; }
        public Nullable<int> NROFACTURAINTERNO { get; set; }
        public Nullable<decimal> IMPORTERESTANTE { get; set; }
        public Nullable<int> IDESTADO { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
