//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Remito()
        {
            this.DetalleRemitoes = new HashSet<DetalleRemito>();
        }
    
        public int NROREMITOINTERNO { get; set; }
        public Nullable<int> NROREMITO { get; set; }
        public string SUCURSAL { get; set; }
        public Nullable<int> IDTIPOREMITO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<int> IDCLIENTE { get; set; }
        public Nullable<int> IDPERSONAL { get; set; }
        public Nullable<int> IDFORMAPAGO { get; set; }
        public Nullable<decimal> BASICO { get; set; }
        public Nullable<decimal> PORCDESC { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> IMPUESTO1 { get; set; }
        public Nullable<decimal> IMPUESTO2 { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<int> IDNOTAPEDIDO { get; set; }
        public string ESTADOREMITO { get; set; }
        public Nullable<int> NROFACTURAINTERNO { get; set; }
        public Nullable<int> IDEMPRESA { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRemito> DetalleRemitoes { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual NotaPedido NotaPedido { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual TipoRemito TipoRemito { get; set; }
    }
}
