//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoporteTecnico
    {
        public int NROTIQUET { get; set; }
        public string FECHASOLICITUD { get; set; }
        public string DESCRIPCION { get; set; }
        public string PRIORIDAD { get; set; }
        public string USUARIO { get; set; }
        public string ESTADOACTUAL { get; set; }
        public string OBSERVACIONES { get; set; }
    }
}
