//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubtipoPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubtipoPago()
        {
            this.DetalleRecibos = new HashSet<DetalleRecibo>();
        }
    
        public int IDSUBTIPOPAGO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> IDTIPOPAGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRecibo> DetalleRecibos { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
