//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suceso
    {
        public int IDSUCESO { get; set; }
        public string EVENTO { get; set; }
        public Nullable<System.DateTime> FECHAHORA { get; set; }
        public string USUARIO { get; set; }
        public int IDESTADO { get; set; }
    
        public virtual EstadoSistema EstadoSistema { get; set; }
    }
}
