//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TesoreriaCaja
    {
        public int NroCaja { get; set; }
        public string Sucursal { get; set; }
        public string NombreCaja { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<decimal> SaldoApertura { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public Nullable<decimal> SaldoCierre { get; set; }
        public Nullable<decimal> IngresoTotal { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> IdEstadoCaja { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    }
}
