//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TesoreriaMovimiento
    {
        public int IdMov { get; set; }
        public string Sucursal { get; set; }
        public Nullable<int> IdTipoMov { get; set; }
        public string TipoMov { get; set; }
        public Nullable<System.DateTime> FechaMov { get; set; }
        public Nullable<decimal> IngresoMov { get; set; }
        public Nullable<decimal> EgresoMov { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> NroCaja { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> NROFACTURAINTERNO { get; set; }
        public Nullable<int> NroReciboInterno { get; set; }
        public string NroFactu { get; set; }
        public string NroRecibo { get; set; }
    }
}
