//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGestion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desterargentina.com.ar;Initial Catalog=DesterGestion2017;Persist Security Info" +
            "=True;User ID=sa;Password=1am45d50G#")]
        public string DesterGestion2017ConnectionString {
            get {
                return ((string)(this["DesterGestion2017ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desterargentina.com.ar;Initial Catalog=DesterGestion2017;Integrated Security=F" +
            "alse;Persist Security Info=False;User ID=sa;Password=1am45d50G#;MultipleActiveRes" +
            "ultSets=True")]
        public string connString {
            get {
                return ((string)(this["connString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desterargentina.com.ar;Initial Catalog=DesterGestion2017;Persist Security Info" +
            "=True;User ID=sa;Password=1am45d50G#")]
        public string DesterGestion2017ConnectionString1 {
            get {
                return ((string)(this["DesterGestion2017ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desterargentina.com.ar;Initial Catalog=DesterGestion2017;Persist Security Info" +
            "=True;User ID=sa;Password=1am45d50G#")]
        public string DesterGestion2017ConnectionString2 {
            get {
                return ((string)(this["DesterGestion2017ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desterargentina.com.ar;Initial Catalog=DesterGestion2017;Persist Security Info" +
            "=True;User ID=sa;Password=1am45d50G#")]
        public string DesterGestion2017ConnectionString3 {
            get {
                return ((string)(this["DesterGestion2017ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desterargentina.com.ar;Initial Catalog=DesterGestion2017;Persist Security Info" +
            "=True;User ID=sa;Password=1am45d50G#")]
        public string DesterGestion2017ConnectionString4 {
            get {
                return ((string)(this["DesterGestion2017ConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=desterargentina.com.ar;Initial Catalog=DesterGestion2017;Persist Security" +
            " Info=True;User ID=sa;Password=1am45d50G#")]
        public string DesterGestion2017ConnectionString5 {
            get {
                return ((string)(this["DesterGestion2017ConnectionString5"]));
            }
        }
    }
}
